# Generated by Django 4.2.13 on 2024-06-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("alert_type", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("details", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("published", models.BooleanField(default=False)),
            ],
        ),
    ]
