# Generated by Django 4.2.13 on 2024-06-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="publish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
