# Generated by Django 4.2.13 on 2024-06-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_alert_publish_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("contact", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("rprkid", models.CharField(max_length=50)),
            ],
        ),
    ]
