# Generated by Django 4.2.13 on 2024-06-17 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=100)),
                ("icon_url", models.URLField()),
                ("slug", models.SlugField(unique=True)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="alerts.alerttype"
            ),
        ),
    ]
