# Generated by Django 4.2.13 on 2024-06-18 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0004_alerttype_alter_alert_alert_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="alerts.location"
            ),
        ),
    ]
