# Generated by Django 4.2.13 on 2024-07-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0007_alter_alert_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
    ]
