# Generated by Django 4.2.13 on 2024-07-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0008_alert_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="kml_file",
            field=models.FileField(blank=True, null=True, upload_to="map_layers/"),
        ),
    ]
