# Generated by Django 4.2.13 on 2024-07-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0009_alert_kml_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="affected_sites",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="website_link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
