# Generated by Django 5.0.8 on 2024-11-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(db_column='Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.AutoField(db_column='ContactId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='create_date',
            field=models.DateTimeField(db_column='CreateDate'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_by',
            field=models.CharField(db_column='CreatedBy', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_column='Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_update',
            field=models.DateTimeField(blank=True, db_column='LastUpdate', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='office_hours',
            field=models.TextField(db_column='OfficeHours'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='office_name',
            field=models.CharField(db_column='OfficeName', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(db_column='Phone', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_by',
            field=models.CharField(blank=True, db_column='UpdatedBy', max_length=100, null=True),
        ),
    ]
