# Generated by Django 5.0.8 on 2024-12-30 05:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0013_remove_location_email_remove_location_id_and_more'),
    ]

    operations = [
    ]
