# Generated by Django 5.0.8 on 2024-12-30 05:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0014_remove_location_email_remove_location_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='location',
            field=models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, to='alerts.location'),
        ),
    ]
